name: Build ESP32 firmware

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python (3.10)
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget make libncurses-dev flex bison gperf \
            python3 python3-pip python3-setuptools python3-serial python3-click \
            python3-cryptography python3-future python3-pyparsing
          pip3 install --upgrade pip

      - name: Clone and install ESP-IDF
        run: |
          mkdir -p $HOME/esp
          cd $HOME/esp
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          # Check out a specific tag/branch, e.g. v5.3.2
          git checkout v5.3.2
          # Make sure submodules match the v5.3.2 commit
          git submodule update --init --recursive

          # Run the ESP-IDF install script (installs toolchains & Python env)
          ./install.sh

          # Source the environment so idf.py is on PATH
          . ./export.sh

          echo "ESP-IDF set up completed"

      - name: Verify ESP-IDF setup
        run: |
          . $HOME/esp/esp-idf/export.sh
          idf.py --version

      - name: Build firmware
        env:
          IDF_PATH: $HOME/esp/esp-idf
        run: |
          . $HOME/esp/esp-idf/export.sh
          idf.py build
            
      - name: Upload firmware binaries
        uses: actions/upload-artifact@v2
        with:
          name: esp32-firmware
          path: |
            build/*.bin
            build/*.elf
            build/*.map


          


