name: Build ESP32 firmware

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up ESP-IDF and build
      uses: espressif/esp-idf-ci-action@v1
      with:
        path: .
        esp_idf_version: v5.3.2
        target: esp32s3
        command: idf.py build

    - name: Debug
      run: |
        echo "PATH=$PATH"
        which idf.py
        
